import { ImageSourcePropType } from 'react-native';

// Stickers
export const STICKER_SOURCES: Record<string, ImageSourcePropType> = {
  sticker1: require('@/assets/images/stickers/sticker1.png'),
  sticker2: require('@/assets/images/stickers/sticker2.png'),
  sticker3: require('@/assets/images/stickers/sticker3.png'),
  sticker4: require('@/assets/images/stickers/sticker4.png'),
  sticker5: require('@/assets/images/stickers/sticker5.png'),
  sticker6: require('@/assets/images/stickers/sticker6.png'),
  sticker7: require('@/assets/images/stickers/sticker7.png'),
  sticker8: require('@/assets/images/stickers/sticker8.png'),
  sticker9: require('@/assets/images/stickers/sticker9.png'),
  sticker10: require('@/assets/images/stickers/sticker10.png'),
  sticker11: require('@/assets/images/stickers/sticker11.png'),
  sticker12: require('@/assets/images/stickers/sticker12.png'),
  sticker13: require('@/assets/images/stickers/sticker13.png'),
  sticker14: require('@/assets/images/stickers/sticker14.png'),
  sticker15: require('@/assets/images/stickers/sticker15.png'),
  sticker16: require('@/assets/images/stickers/sticker16.png'),
  sticker17: require('@/assets/images/stickers/sticker17.png'),
  sticker18: require('@/assets/images/stickers/sticker18.png'),
  sticker19: require('@/assets/images/stickers/sticker19.png'),
  sticker20: require('@/assets/images/stickers/sticker20.png'),
  sticker21: require('@/assets/images/stickers/sticker21.png'),
  sticker22: require('@/assets/images/stickers/sticker22.png'),
  sticker23: require('@/assets/images/stickers/sticker23.png'),
  sticker24: require('@/assets/images/stickers/sticker24.png'),
  sticker25: require('@/assets/images/stickers/sticker25.png'),
  sticker26: require('@/assets/images/stickers/sticker26.png'),
  sticker27: require('@/assets/images/stickers/sticker27.png'),
  sticker28: require('@/assets/images/stickers/sticker28.png'),
  sticker29: require('@/assets/images/stickers/sticker29.png'),
  sticker30: require('@/assets/images/stickers/sticker30.png'),
  sticker31: require('@/assets/images/stickers/sticker31.png'),
  sticker33: require('@/assets/images/stickers/sticker33.png'),
  sticker34: require('@/assets/images/stickers/sticker34.png'),
  sticker35: require('@/assets/images/stickers/sticker35.png'),
  sticker37: require('@/assets/images/stickers/sticker37.png'),
  sticker38: require('@/assets/images/stickers/sticker38.png'),
  sticker39: require('@/assets/images/stickers/sticker39.png'),
  sticker40: require('@/assets/images/stickers/sticker40.png'),
  sticker41: require('@/assets/images/stickers/sticker41.png'),
  sticker42: require('@/assets/images/stickers/sticker42.png'),
  sticker43: require('@/assets/images/stickers/sticker43.png'),
  sticker44: require('@/assets/images/stickers/sticker44.png'),
  sticker45: require('@/assets/images/stickers/sticker45.png'),
  sticker46: require('@/assets/images/stickers/sticker46.png'),
  sticker47: require('@/assets/images/stickers/sticker47.png'),
  sticker48: require('@/assets/images/stickers/sticker48.png'),
  sticker49: require('@/assets/images/stickers/sticker49.png'),
  sticker50: require('@/assets/images/stickers/sticker50.png'),
  sticker51: require('@/assets/images/stickers/sticker51.png'),
  sticker52: require('@/assets/images/stickers/sticker52.png'),
  sticker53: require('@/assets/images/stickers/sticker53.png'),
  sticker54: require('@/assets/images/stickers/sticker54.png'),
};

// Lista de IDs de stickers disponibles
export const AVAILABLE_STICKER_IDS = Object.keys(STICKER_SOURCES) as (keyof typeof STICKER_SOURCES)[];
