import { StyleSheet } from 'react-native';
import { uiColors } from '@/constants/colors';

export const diaryStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: uiColors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  backButton: {
    padding: 8,
    width: 40,
    alignItems: 'flex-start',
    marginTop: 30,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: uiColors.danger,
    flex: 1,
    textAlign: 'center',
    marginTop: 30,
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 24,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  diaryPreview: {
    alignItems: 'center',
    marginBottom: 40,
  },
  diary: {
    width: 160,
    height: 200,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    position: 'relative',
  },
  diaryBinding: {
    position: 'absolute',
    right: 12,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: 'rgba(14, 13, 13, 0.3)',
  },
  inputContainer: {
    marginBottom: 32,
    width: 280,
    marginLeft: 8,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: uiColors.danger,
    marginBottom: 8,
  },
  nameInput: {
    backgroundColor: uiColors.white,
    width: 280,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginLeft: 11,
    marginBottom: -20,
    fontSize: 16,
    color: uiColors.gray,
    borderWidth: 2,
    borderColor: uiColors.grayO,
    shadowColor: uiColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  colorSection: {
    marginBottom: 45,
    margin: 7,
    gap: 5,
    marginLeft: 7,
    marginRight: 7,
  },
  colorLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: uiColors.danger,
    marginBottom: 10,
  },
  saveButton: {
    backgroundColor: uiColors.primary,
    height: 50,
    width: 120,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -25,
    marginBottom: 10,
    marginLeft: 100,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
});
