// styles/editCoverStyles.ts
import { uiColors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const editCoverStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: uiColors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 20,
    backgroundColor: uiColors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: uiColors.gray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  closeIcon: {
    fontSize: 19,
    color: uiColors.white,
    fontWeight: "600",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: uiColors.danger,
  },
  saveButton: {
    width: 30,
    height: 30,
    borderRadius: 20,
    backgroundColor: uiColors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: uiColors.gray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  saveIcon: {
    fontSize: 13,
    color: uiColors.white,
    fontWeight: "600",
  },
  content: {
    flex: 1,
    alignItems: "center",
    paddingTop: 40,
  },
  diaryPreview: {
    alignItems: "center",
    marginBottom: 30,
  },
  diary: {
    width: 160,
    height: 200,
    borderRadius: 8,
    shadowColor: uiColors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    position: "relative",
  },
  diaryBinding: {
    position: "absolute",
    right: 20,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: uiColors.grayLight,
  },
  inputContainer: {
    width: "100%",
    paddingHorizontal: 30,
    marginBottom: 25,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: uiColors.danger,
    marginBottom: 10,
  },
  nameInput: {
    backgroundColor: uiColors.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: uiColors.gray,
    borderWidth: 2,
    borderColor: uiColors.grayO,
    shadowColor: uiColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  colorSection: {
    width: "100%",
    paddingHorizontal: 30,
  },
  colorLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: uiColors.danger,
    marginBottom: 20,
  },
  deleteSection: {
    position: "absolute",
    bottom: 40,
    width: "100%",
    alignItems: "center",
  },
  deleteButton: {
    paddingVertical: 12,
    paddingHorizontal: 30,
  },
  deleteButtonText: {
    fontSize: 14,
    color: uiColors.gray,
    textDecorationLine: "underline",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF8F0",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#999",
  },
});