// styles/editCoverStyles.ts
import { uiColors } from '@/constants/colors';
import { StyleSheet } from 'react-native';

export const editCoverStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: uiColors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingBottom: 20,
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginTop: 30,
  },
  closeIcon: {
    fontSize: 19,
    color: uiColors.white,
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: uiColors.danger,
    marginTop: 30,
  },
  saveButton: {
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  saveIcon: {
    fontSize: 13,
    color: uiColors.white,
    fontWeight: '600',
    marginTop: 30,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 40,
  },
  diaryPreview: {
    alignItems: 'center',
    marginBottom: 30,
  },
  diary: {
    width: 160,
    height: 200,
    borderRadius: 8,
    shadowColor: uiColors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    position: 'relative',
  },
  diaryBinding: {
    position: 'absolute',
    right: 20,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: 'rgba(96, 93, 93, 0.3)',
  },
  // Línea divisoria sutil
  bookDivider: {
    position: 'absolute',
    left: 22,
    top: 10,
    bottom: 10,
    width: 1.2,
    backgroundColor: 'rgba(96, 93, 93, 0.3)',
    borderRadius: 1,
  },
  inputContainer: {
    width: '100%',
    paddingHorizontal: 30,
    marginBottom: 25,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: uiColors.danger,
    marginBottom: 10,
  },
  nameInput: {
    backgroundColor: uiColors.white,
    width: 280,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginLeft: 11,
    fontSize: 16,
    color: uiColors.gray,
    borderWidth: 2,
    borderColor: uiColors.grayO,
    shadowColor: uiColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  colorSection: {
    width: '100%',
    paddingHorizontal: 30,
    marginBlock: 0,
  },
  colorLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: uiColors.danger,
    marginBottom: 10,
  },
  deleteSection: {
    position: 'absolute',
    bottom: 40,
    width: '100%',
    alignItems: 'center',
  },
  deleteButton: {
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginBlock: 20,
  },
  deleteButtonText: {
    fontSize: 14,
    color: uiColors.gray,
    textDecorationLine: 'underline',
    marginBlock: 0,
    marginBottom: 0,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF8F0',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#999',
  },
});
