import { uiColors } from '@/constants/colors';
import { StyleSheet } from 'react-native';
import { rw, rh, rf } from '@/utils/responsive';

export const editCoverStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: uiColors.background,
    paddingHorizontal: rw(10),
    paddingTop: 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: rw(16),
    paddingVertical: rh(12),
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingTop: rh(23),
   
  },
  closeButton: {
    padding: rw(8),
    width: rw(44),
    height: rw(44),
    borderRadius: rw(22),
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeIcon: {
    fontSize: rf(20),
    color: uiColors.white,
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: rf(18),
    fontWeight: '600',
    color: uiColors.danger,
    flex: 1,
    textAlign: 'center',
    paddingTop: rh(23),
  },
  saveButton: {
    padding: rw(8),
    width: rw(44),
    height: rw(44),
    borderRadius: rw(22),
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveIcon: {
    fontSize: rf(18),
    color: uiColors.white,
    fontWeight: '600',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingTop: rh(20),
  },
  diaryPreview: {
    alignItems: 'center',
    marginBottom: rh(30),
  },
  diary: {
    width: rw(160),
    height: rh(200),
    borderRadius: rw(8),
    shadowColor: uiColors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    position: 'relative',
  },
  diaryBinding: {
    position: 'absolute',
    right: rw(12),
    top: 0,
    bottom: 0,
    width: rw(3),
    backgroundColor: 'rgba(96, 93, 93, 0.3)',
  },
  bookDivider: {
    position: 'absolute',
    left: rw(22),
    top: rh(10),
    bottom: rh(10),
    width: rw(1.2),
    backgroundColor: 'rgba(96, 93, 93, 0.3)',
    borderRadius: rw(1),
  },
  inputContainer: {
    width: '100%',
    paddingHorizontal: rw(25),
    marginBottom: rh(20),
  },
  inputLabel: {
    fontSize: rf(16),
    fontWeight: '600',
    color: uiColors.danger,
    marginBottom: rh(14),
  },
  nameInput: {
    backgroundColor: uiColors.white,
    width: '100%',
    borderRadius: rw(12),
    paddingHorizontal: rw(16),
    paddingVertical: rh(14),
    fontSize: rf(16),
    color: uiColors.gray,
    borderWidth: 2,
    borderColor: uiColors.grayO,
    shadowColor: uiColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  colorSection: {
    width: '100%',
    paddingHorizontal: rw(25),
    marginBottom: rh(10),
  },
  colorLabel: {
    fontSize: rf(16),
    fontWeight: '600',
    color: uiColors.danger,
    marginBottom: rh(10),
  },
  deleteSection: {
    marginTop: rh(20),
    width: '100%',
    alignItems: 'center',
  },
  deleteButton: {
    paddingVertical: rh(12),
    paddingHorizontal: rw(30),
  },
  deleteButtonText: {
    fontSize: rf(14),
    color: uiColors.gray,
    textDecorationLine: 'underline',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: uiColors.background,
  },
  loadingText: {
    marginTop: rh(14),
    fontSize: rf(14),
    color: '#999',
  },
});