import { StyleSheet } from "react-native";
import { uiColors } from "@/constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    position: "relative",
  },
  backButton: {
    position: "absolute",
    left: 20,
    paddingHorizontal: 8,
    height: "100%",
    justifyContent: "center",
  },
  rightButton: {
    position: "absolute",
    right: 20,
    paddingHorizontal: 8,
    height: "100%",
    justifyContent: "center",
  },
  backIcon: {
    fontSize: 18,
    color: uiColors.danger,
  },
  nextIcon: {
    fontSize: 18,
    color: uiColors.danger,
  },
  leftGroup: {
    position: "absolute",
    left: 16,
    top: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  navButton: {
    padding: 10,
    marginHorizontal: 4,
  },
  checkButton: {
    position: "absolute",
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  checkIcon: {
    fontSize: 18,
    color: uiColors.danger,
  },
  titleWrap: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
  },
  canvas: {
    flex: 1,
  },
  toolbar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 24,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  toolCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.6)",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 6,
  },
  toolPlain: {
    paddingHorizontal: 6,
    paddingVertical: 6,
    marginHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  toolIcon: {
    fontSize: 20,
    color: uiColors.black,
  },

  // Estilos del modal de dibujo
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 80,
  },
  modalMenuContainer: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 10,
    flexDirection: "row",
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10,
    marginHorizontal: 20,
  },
  modalOption: {
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    flex: 1,
    borderRadius: 15,
    minWidth: 80,
  },
  modalOptionText: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: "600",
    color: "#333",
  },

  drawModalContent: {
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 0,
    height: 145,
    marginLeft: 10,
    marginRight: 10,
    width: 380,
  },
  toolsSection: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 10,
  },
  toolButton: {
    alignItems: "center",
    paddingVertical: 5,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: "#f5f5f5",
    minWidth: 90,
  },
  toolButtonActive: {
    backgroundColor: "#e3f2fd",
    borderWidth: 2,
    borderColor: "#2196F3",
  },
  toolLabel: {
    marginTop: 6,
    fontSize: 12,
    color: "#333",
    fontWeight: "500",
  },
  toolsAndColorsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  toolsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  toolButtonCompact: {
    alignItems: "center",
    marginRight: 3,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: "#f5f5f5",
  },
  toolLabelCompact: {
    fontSize: 11,
    color: "#333",
    marginTop: 3,
  },
  colorsSection: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 15,
    marginBottom: 25,
  },
  colorButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "transparent",
  },
  colorButtonActive: {
    borderColor: "#2196F3",
    borderWidth: 2,
  },
  colorsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  colorButtonCompact: {
    width: 26,
    height: 26,
    borderRadius: 13,
    marginHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  thicknessSliderSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 10,
  },
  thicknessSection: {
    marginBottom: 25,
  },

  // 🔹 AQUÍ está el label alineado totalmente a la derecha
  sectionLabel: {
    fontSize: 14,
    color: "#666",
    textAlign: "right",
    alignSelf: "flex-end",
    marginRight: 10,
    flexShrink: 1,
  },

  thicknessSlider: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  thicknessOption: {
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
    backgroundColor: "#f5f5f5",
  },
  thicknessOptionActive: {
    backgroundColor: "#e3f2fd",
    borderWidth: 2,
    borderColor: "#2196F3",
  },
  thicknessDot: {
    backgroundColor: "#333",
  },
  sliderWrapper: {
    flex: 1,
    alignItems: "stretch",
  },
  slider: {
    width: "100%",
    height: 47,
  },
  dotsRow: {
    position: "absolute",
    top: 18,
    left: 8,
    right: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 10,
  },
  colorCircleSelected: {
    borderColor: "#333",
    borderWidth: 2.5,
  },

  // Modal de texto
  textModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  textModalBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textOptionsContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    padding: 20,
    minHeight: 350,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  textOptionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  textIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  textIconLetter: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333",
  },
  textOptionsTitle: {
    fontSize: 16,
    fontWeight: "400",
    color: "#333",
  },
  textInput: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    padding: 12,
    minHeight: 70,
    fontSize: 16,
    color: "#333",
    marginBottom: 20,
    textAlignVertical: "top",
    backgroundColor: "#fafafa",
  },
  colorSection: {
    marginBottom: 20,
  },
  colorCircle: {
    width: 28,
    height: 28,
    borderRadius: 16,
    marginRight: 13,
    borderWidth: 2,
    borderColor: "transparent",
  },
  fontSection: {
    marginBottom: 20,
  },
  fontButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#f5f5f5",
    marginRight: 10,
    minWidth: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  fontButtonSelected: {
    backgroundColor: "#e0e0e0",
    borderWidth: 1,
    borderColor: "#ccc",
  },
  fontButtonText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "400",
  },
  fontButtonTextSelected: {
    color: "#333",
    fontWeight: "500",
  },
  addTextButton: {
    backgroundColor: "#2467a5",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  addTextButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
});
